apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-api-deployment
  labels:
    app: billing-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-api
  template:
    metadata:
      labels:
        app: billing-api
    spec:
      serviceAccountName: billing-sa
      containers:
      - name: billing-api
        image: 258531703731.dkr.ecr.us-east-1.amazonaws.com/billing-api:latest # This will be your registry image url
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY
          value: "dummy"
        - name: SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY
          value: "dummy"
        - name: APP_SQS_PAYMENT_NOTIFICATION_QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: billing-secrets
              key: PAYMENT_NOTIFICATION_QUEUE_URL
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: billing-secrets
              key: MONGODB_URI
        - name: PAYMENT_NOTIFICATION_QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: billing-secrets
              key: PAYMENT_NOTIFICATION_QUEUE_URL
              optional: true
        - name: PAYMENT_APPROVED_TOPIC_ARN
          valueFrom:
            secretKeyRef:
              name: billing-secrets
              key: PAYMENT_APPROVED_TOPIC_ARN
              optional: true
        - name: PAYMENT_FAILED_TOPIC_ARN
          valueFrom:
            secretKeyRef:
              name: billing-secrets
              key: PAYMENT_FAILED_TOPIC_ARN
              optional: true
        envFrom:
        - secretRef:
            name: billing-secrets
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
