apiVersion: v1
kind: Secret
metadata:
  name: billing-secrets
type: Opaque
data:
  # Base64 encoded values
  MONGODB_URI: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvYmlsbGluZ19kYg==
  NGROK_AUTHTOKEN: MzlkaVRRenFRc0Q5dFVrVWhOTkVTdGZUNTNPXzNLY2JHVHc1bmhQM01tVFdXZHB0aw==
  MERCADO_PAGO_ACCESS_TOKEN: QVBQX1VTUi0yMTQxMTE3NjQ3NjQ5ODUtMDIxMzIxLTVmMzBkMDAzMTYxMmY0NTMzZTMwMWFkNmNiNTYyN2YzLTMxOTY1Mzc0NTA=
  MERCADOPAGO_NOTIFICATION_URL: aHR0cHM6Ly90cmluaC1kaXNwZW5zaWJsZS1pbnN0cnVjdGl2ZWx5Lm5ncm9rLWZyZWUuZGV2L2FwaS92MS93ZWJob29rcy9tZXJjYWRvcGFnbw==
