apiVersion: v1
kind: ServiceAccount
metadata:
  name: billing-sa
  namespace: default
  annotations:
    # This ARN will be populated dynamically via a CD pipeline or replaced manually with the Terraform output
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/billing-api-irsa
